// <auto-generated />
namespace BirdsSoundsClassifier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddingImagesFunction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingImagesFunction));
        
        string IMigrationMetadata.Id
        {
            get { return "201904140354191_Adding-ImagesFunction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
